spring:
  datasource:
    initialize: false
    master:
      type: com.alibaba.druid.pool.DruidDataSource
      url: jdbc:sqlserver://192.168.17.81:1433;DatabaseName=CRM_MSCRM
      driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
      username: sa
      password: '@DrmSWL2018'
    extension:
      type: com.alibaba.druid.pool.DruidDataSource
      url: jdbc:sqlserver://192.168.17.82:1433;DatabaseName=CRM_Extension
      driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
      username: sa
      password: '@DrmSWL2018'
    druid:
      initial-size: 10
      max-active: 30000
      min-idle: 5
      test-on-borrow: false
      test-while-idle: true
      db-type: sqlserver
    type: com.alibaba.druid.pool.DruidDataSource
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
mybatis:
  mapper-locations: classpath:mapper/*.xml
mapper:
  identity: SQLSERVER
pagehelper:
  helper-dialect: sqlserver
  reasonable: false
  support-methods-arguments: true
  params: count=countSql
drmswl:
  crm:
    url: http://192.168.17.80:60808/
    basedataurl: http://192.168.17.80:60808/
    data:
      ownerid: CFA819C9-FE87-E911-B022-005056B07343
      owningbusinessunit: DDA119C9-FE87-E911-B022-005056B07343
ribbon:
  ReadTimeout: 20000
  ConnectTimeout: 20000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 1
  eureka:
    enabled: true
  eager-load:
    enabled: true
    clients: user-pos-service,trade-pos-service,promotion-pos-service,message-service,base-service,promotion-service,trade-service,analysis-service
feign:
  hystrix:
    enabled: true
  httpclient:
    enabled: true
hystrix:
  threadpool:
    default:
      coreSize: 5000
  command:
    default:
      fallback:
        enabled: true
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 30000 #缺省为1000
